"""Apache Kafka broker connection schema.

Stored config uses native Kafka / librdkafka keys so Confluent, Aiven, MSK,
and local brokers share one client path.
"""

from app.connectors.schemas.base import FieldDef, Schema

_SASL = {"field": "security_protocol", "in": ["SASL_PLAINTEXT", "SASL_SSL"]}
_TLS = {"field": "security_protocol", "in": ["SSL", "SASL_SSL"]}


KAFKA_SCHEMA = Schema(
    subtype="kafka",
    label="Apache Kafka",
    fields=(
        FieldDef(
            id="bootstrap_servers",
            label="Bootstrap Servers",
            kc_key="bootstrap.servers",
            test_key="bootstrap.servers",
            importance="required",
            placeholder="broker1:9092,broker2:9092",
            doc="Comma-separated list of Kafka broker addresses.",
            group="connection", order=10,
        ),
        FieldDef(
            id="security_protocol",
            label="Security Protocol",
            kc_key="security.protocol",
            test_key="security.protocol",
            type="enum",
            options=("PLAINTEXT", "SSL", "SASL_PLAINTEXT", "SASL_SSL"),
            importance="required",
            default="PLAINTEXT",
            doc="PLAINTEXT for local brokers. Cloud clusters typically use SASL_SSL.",
            group="connection", order=20,
        ),
        FieldDef(
            id="client_id",
            label="Client ID",
            kc_key="client.id",
            test_key="client.id",
            importance="advanced",
            default="streambridge",
            placeholder="streambridge",
            doc="Identifier this app presents to the cluster.",
            group="connection", order=30,
        ),

        FieldDef(
            id="sasl_mechanism",
            label="SASL Mechanism",
            kc_key="sasl.mechanism",
            test_key="sasl.mechanism",
            type="enum",
            options=("PLAIN", "SCRAM-SHA-256", "SCRAM-SHA-512", "OAUTHBEARER", "GSSAPI"),
            importance="advanced",
            default="PLAIN",
            doc="Required when security.protocol is SASL_*. Confluent Cloud uses PLAIN.",
            group="auth", order=10,
            visible_when=_SASL,
        ),
        FieldDef(
            id="username",
            label="SASL Username",
            kc_key="sasl.username",
            test_key="sasl.username",
            importance="advanced",
            placeholder="cluster-api-key",
            doc="SASL username. For Confluent Cloud, this is the API key.",
            group="auth", order=20,
            visible_when=_SASL,
        ),
        FieldDef(
            id="password",
            label="SASL Password",
            kc_key="sasl.password",
            test_key="sasl.password",
            type="password",
            secret=True,
            importance="advanced",
            placeholder="••••••••",
            doc="SASL password. For Confluent Cloud, this is the API secret.",
            group="auth", order=30,
            visible_when=_SASL,
        ),

        FieldDef(
            id="ssl_ca_location",
            label="SSL CA Bundle",
            kc_key="ssl.ca.location",
            test_key="ssl.ca.location",
            importance="advanced",
            placeholder="/etc/ssl/kafka-ca.pem",
            doc="Path to CA certificate bundle used to verify broker certs.",
            group="tls", order=10,
            visible_when=_TLS,
        ),
        FieldDef(
            id="ssl_certificate_location",
            label="SSL Client Certificate",
            kc_key="ssl.certificate.location",
            test_key="ssl.certificate.location",
            importance="advanced",
            placeholder="/etc/ssl/kafka-client.crt",
            doc="PEM client certificate for mutual TLS.",
            group="tls", order=20,
            visible_when=_TLS,
        ),
        FieldDef(
            id="ssl_key_location",
            label="SSL Client Key",
            kc_key="ssl.key.location",
            test_key="ssl.key.location",
            importance="advanced",
            placeholder="/etc/ssl/kafka-client.key",
            doc="PEM private key for mutual TLS.",
            group="tls", order=30,
            visible_when=_TLS,
        ),
        FieldDef(
            id="ssl_key_password",
            label="SSL Key Password",
            kc_key="ssl.key.password",
            test_key="ssl.key.password",
            type="password",
            secret=True,
            importance="advanced",
            placeholder="••••••••",
            doc="Passphrase for ssl.key.location, if the key is encrypted.",
            group="tls", order=40,
            visible_when=_TLS,
        ),
        FieldDef(
            id="ssl_endpoint_identification_algorithm",
            label="SSL Endpoint Identification",
            kc_key="ssl.endpoint.identification.algorithm",
            test_key="ssl.endpoint.identification.algorithm",
            type="enum",
            options=("https", "none"),
            importance="advanced",
            default="https",
            doc="Set to none to skip hostname verification (some local TLS brokers).",
            group="tls", order=50,
            visible_when=_TLS,
        ),
    ),
)
