"""Kafka Connect REST API connection schema."""

from app.connectors.schemas.base import FieldDef, Schema


KAFKA_CONNECT_SCHEMA = Schema(
    subtype="kafka-connect",
    label="Kafka Connect",
    fields=(
        # ── Required ───────────────────────────────────────────────────────
        FieldDef(
            id="deployment",
            label="Deployment",
            kc_key="deployment",
            test_key="deployment",
            type="enum",
            options=("connect", "kubernetes"),
            default="connect",
            importance="required",
            doc="How StreamBridge deploys this connector. Connect: posts the config straight to the Kafka Connect REST API. Kubernetes: creates or updates a Strimzi KafkaConnector in your namespace for the operator to apply. Either way, live status, tasks, offsets, and restart are read from the Connect URL.",
            group="connection", order=5,
        ),
        FieldDef(
            id="url",
            label="Connect URL",
            kc_key="url",
            test_key="url",
            importance="required",
            placeholder="http://kafka-connect:8083",
            doc="Kafka Connect REST API. Connect deployments create connectors here. Kubernetes deployments read status, tasks, and offsets here.",
            group="connection", order=10,
        ),
        FieldDef(
            id="auth_type",
            label="Connect authentication",
            kc_key="auth_type",
            test_key="auth_type",
            type="enum",
            options=("none", "basic"),
            default="none",
            importance="recommended",
            doc="Authentication for the Connect URL. Basic is a username and password.",
            group="auth", order=10,
        ),
        FieldDef(
            id="username",
            label="Username",
            kc_key="username",
            test_key="username",
            importance="required",
            placeholder="connect-user",
            doc="HTTP Basic username for the Connect URL.",
            group="auth", order=20,
            visible_when={"field": "auth_type", "in": ["basic"]},
        ),
        FieldDef(
            id="password",
            label="Password",
            kc_key="password",
            test_key="password",
            type="password",
            secret=True,
            importance="required",
            placeholder="••••••••",
            doc="HTTP Basic password for the Connect URL.",
            group="auth", order=30,
            visible_when={"field": "auth_type", "in": ["basic"]},
        ),
        FieldDef(
            id="api_host",
            label="Kubernetes API host",
            kc_key="api_host",
            test_key="api_host",
            importance="required",
            placeholder="https://xxxx.eks.amazonaws.com",
            doc="Cluster API server. The namespace is added to the path. One host covers every namespace.",
            group="kubernetes", order=10,
            visible_when={"field": "deployment", "in": ["kubernetes"]},
        ),
        FieldDef(
            id="namespace",
            label="Namespace",
            kc_key="namespace",
            test_key="namespace",
            importance="required",
            placeholder="kafka",
            doc="Namespace of the Kafka Connect cluster. The connector is created here.",
            group="kubernetes", order=20,
            visible_when={"field": "deployment", "in": ["kubernetes"]},
        ),
        FieldDef(
            id="cluster",
            label="Connect cluster",
            kc_key="cluster",
            test_key="cluster",
            importance="required",
            placeholder="my-connect-cluster",
            doc="Strimzi KafkaConnect name. Stored as the strimzi.io/cluster label.",
            group="kubernetes", order=30,
            visible_when={"field": "deployment", "in": ["kubernetes"]},
        ),
        FieldDef(
            id="api_token",
            label="Bearer token",
            kc_key="api_token",
            test_key="api_token",
            type="password",
            secret=True,
            importance="required",
            placeholder="••••••••",
            doc="Service account token for the Kubernetes API. A 401 means the token was rejected. A 403 means it cannot change connectors in this namespace.",
            group="kubernetes", order=40,
            visible_when={"field": "deployment", "in": ["kubernetes"]},
        ),

        # ── Advanced: TLS ─────────────────────────────────────────────────
        FieldDef(
            id="verify_ssl",
            label="Verify TLS Certificate",
            kc_key="verify.ssl",
            test_key="verify_ssl",
            type="boolean",
            importance="advanced",
            default=True,
            doc="Set to false only for self-signed certificates in dev environments.",
            cast=lambda v: "true" if str(v).lower() in ("true", "1", "yes", "on") else "false",
            test_transform=lambda v: str(v).lower() in ("true", "1", "yes", "on"),
            group="tls", order=10,
        ),
        FieldDef(
            id="timeout_seconds",
            label="Request Timeout (s)",
            kc_key="timeout",
            test_key="timeout",
            type="number",
            cast=int,
            default=10,
            importance="advanced",
            placeholder="10",
            doc="Seconds before a request to Kafka Connect times out.",
            group="tuning", order=10,
        ),
    ),
)
